name: Django App Validation

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Run Linter (Flake8)
        run: docker compose run --rm app sh -c "flake8"

      - name: Run Tests
        run: docker compose run --rm app sh -c "python manage.py test"